services:
  - type: web
    name: crm-api
    env: node
    plan: free
    buildCommand: cd ../.. && pnpm install && pnpm --filter @crm/shared build && cd apps/api && pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        sync: false  # Set this in Render dashboard
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
      - key: REDIS_URL
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: JWT_REFRESH_SECRET
        sync: false  # Set this in Render dashboard

